"""add is_group to conversations

Revision ID: 39cf4a7e5cf7
Revises: 32aad94d7309
Create Date: 2026-03-27 11:35:36.626284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39cf4a7e5cf7'
down_revision: Union[str, None] = '32aad94d7309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_group', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_group')
    # ### end Alembic commands ###
