"""initial

Revision ID: 6fb1a8ecdd13
Revises: 
Create Date: 2026-03-27 01:29:43.528675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fb1a8ecdd13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contact_rules',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contact_jid', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=10), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_jid', name='uq_user_contact')
    )
    op.create_index(op.f('ix_contact_rules_contact_jid'), 'contact_rules', ['contact_jid'], unique=False)
    op.create_index(op.f('ix_contact_rules_user_id'), 'contact_rules', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contact_jid', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_contact_jid'), 'conversations', ['contact_jid'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('openai_api_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('claude_api_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('debounce_seconds', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_tone', sa.String(length=50), nullable=False),
    sa.Column('agent_instructions', sa.Text(), nullable=True),
    sa.Column('response_length', sa.String(length=20), nullable=False),
    sa.Column('avoid_markdown', sa.Boolean(), nullable=False),
    sa.Column('use_simple_language', sa.Boolean(), nullable=False),
    sa.Column('avoid_oversharing', sa.Boolean(), nullable=False),
    sa.Column('contact_access_mode', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('whatsapp_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_sessions_user_id'), 'whatsapp_sessions', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_stored_in_memory', sa.Boolean(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_whatsapp_sessions_user_id'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_jid'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contact_rules_user_id'), table_name='contact_rules')
    op.drop_index(op.f('ix_contact_rules_contact_jid'), table_name='contact_rules')
    op.drop_table('contact_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
